colors: 
  normal: 
    black: '#3C3836'    # Black (Host)
    red: '#EA6962'    # Red (Syntax string)
    green: '#A9B665'    # Green (Command)
    yellow: '#D8A657'    # Yellow (Command second)
    blue: '#7DAEA3'    # Blue (Path)
    magenta: '#D3869B'    # Magenta (Syntax var)
    cyan: '#89B482'    # Cyan (Prompt)
    white: '#D4BE98'    # White

  bright: 
    black: '#3C3836'    # Bright Black
    red: '#EA6962'    # Bright Red (Command error)
    green: '#A9B665'    # Bright Green (Exec)
    yellow: '#D8A657'    # Bright Yellow
    blue: '#7DAEA3'    # Bright Blue (Folder)
    magenta: '#D3869B'    # Bright Magenta
    cyan: '#89B482'    # Bright Cyan
    white: '#D4BE98'    # Bright White

  background: '#282828'  # Background
  foreground: '#D4BE98'  # Foreground (Text)

  cursor: '#D4BE98'      # Cursor

overrides: 
  tmux: 
    color: '#D4BE98'
