colors: 
  normal: 
    black: '#292D3E'    # Black (Host)
    red: '#F07178'    # Red (Syntax string)
    green: '#C3E88D'    # Green (Command)
    yellow: '#FFCB6B'    # Yellow (Command second)
    blue: '#82AAFF'    # Blue (Path)
    magenta: '#C792EA'    # Magenta (Syntax var)
    cyan: '#60ADEC'    # Cyan (Prompt)
    white: '#ABB2BF'    # White

  bright:
    black: '#959DCB'    # Bright Black
    red: '#F07178'    # Bright Red (Command error)
    green: '#C3E88D'    # Bright Green (Exec)
    yellow: '#FF5572'    # Bright Yellow
    blue: '#82AAFF'    # Bright Blue (Folder)
    magenta: '#FFCB6B'    # Bright Magenta
    cyan: '#676E95'    # Bright Cyan
    white: '#FFFEFE'    # Bright White

  background: '#292D3E'  # Background
  foreground: '#BFC7D5'  # Foreground (Text)

  cursor: '#BFC7D5'      # Cursor

overrides: 
  nvim:
    theme: palenightfall
