colors: 
  normal:
    black: '#414868'    # Black (Host)
    red: '#F7768E'    # Red (Syntax string)
    green: '#9ECE6A'    # Green (Command)
    yellow: '#E0AF68'    # Yellow (Command second)
    blue: '#7AA2F7'    # Blue (Path)
    magenta: '#BB9AF7'    # Magenta (Syntax var)
    cyan: '#7DCFFF'    # Cyan (Prompt)
    white: '#A9B1D6'    # White

  bright:
    black: '#414868'    # Bright Black
    red: '#F7768E'    # Bright Red (Command error)
    green: '#9ECE6A'    # Bright Green (Exec)
    yellow: '#E0AF68'    # Bright Yellow
    blue: '#7AA2F7'    # Bright Blue (Folder)
    magenta: '#BB9AF7'    # Bright Magenta
    cyan: '#7DCFFF'    # Bright Cyan
    white: '#C0CAF5'    # Bright White

  background: '#1A1B26'  # Background
  foreground: '#C0CAF5'  # Foreground (Text)

  cursor: '#C0CAF5'      # Cursor

overrides:
  tmux: 
    color: '#7AA2F7'
