colors:
  normal: 
    black: '#000000'    # Black (Host)
    red: '#CC6666'    # Red (Syntax string)
    green: '#B5BD68'    # Green (Command)
    yellow: '#F0C674'    # Yellow (Command second)
    blue: '#81A2BE'    # Blue (Path)
    magenta: '#B293BB'    # Magenta (Syntax var)
    cyan: '#8ABEB7'    # Cyan (Prompt)
    white: '#FFFEFE'    # White

  bright:
    black: '#3D3F41'    # Bright Black
    red: '#CC6666'    # Bright Red (Command error)
    green: '#B5BD68'    # Bright Green (Exec)
    yellow: '#F0C574'    # Bright Yellow
    blue: '#80A1BD'    # Bright Blue (Folder)
    magenta: '#B294BA'    # Bright Magenta
    cyan: '#8ABDB6'    # Bright Cyan
    white: '#FFFEFE'    # Bright White

  background: '#1D1F21'  # Background
  foreground: '#C5C8C6'  # Foreground (Text)

  cursor: '#C4C8C5'      # Cursor

overrides:
  tmux:
    color: '#C5C8C6'
