# NVIM
- { key: "s", mods: [ "CMD" ], action: "\x1b\x3a\x77\x0a" } # save in nvim
- { key: "z", mods: [ "CMD", "SHIFT" ], action: "\x12" } # redo in nvim
- { key: "z", mods: [ "CMD" ], action: "\x1bu" } # undo in nvim
- { key: "w", mods: [ "CMD" ], action: "\x1b\x3a\x62\x64\x0a" } # write in nvim
- { key: "l", mods: [ "CMD", "CTRL", "SHIFT" ], action: "\x1b\x20\x77\x7c\x0a" } # split left in nvim
- { key: "j", mods: [ "CMD", "CTRL", "SHIFT" ], action: "\x1b\x20\x77\x2d\x0a" } # split down in nvim

# TMUX
- { key: "l", mods: [ "CMD", "SHIFT" ], action: "\x02l" } # move pane left
- { key: "h", mods: [ "CMD", "SHIFT" ], action: "\x02h" } # move pane right
- { key: "j", mods: [ "CMD", "SHIFT" ], action: "\x02j" } # move pane down
- { key: "k", mods: [ "CMD", "SHIFT" ], action: "\x02k" } # move pane up
- { key: "LBracket", mods: [ "CMD", "SHIFT" ], action: "\x02p" } # previous window
- { key: "RBracket", mods: [ "CMD", "SHIFT" ], action: "\x02n" } # next window
- { key: "Semicolon", mods: [ "CMD" ], action: "\x02:" } # tmux command
- { key: "p", mods: [ "CMD", "SHIFT" ], action: "\x02F" } # tmux fzf 
- { key: "Key1", mods: [ "CMD" ], action: "\x021" } # window 1
- { key: "Key2", mods: [ "CMD" ], action: "\x022" } # window 2
- { key: "Key3", mods: [ "CMD" ], action: "\x023" } # window 3
- { key: "Key4", mods: [ "CMD" ], action: "\x024" } # window 4
- { key: "Key5", mods: [ "CMD" ], action: "\x025" } # window 5
- { key: "Key6", mods: [ "CMD" ], action: "\x026" } # window 6
- { key: "Key7", mods: [ "CMD" ], action: "\x027" } # window 7
- { key: "Key8", mods: [ "CMD" ], action: "\x028" } # window 8
- { key: "Key9", mods: [ "CMD" ], action: "\x029" } # window 9
- { key: "Tab", mods: [ "CTRL" ], action: "\x02n" } # next window
- { key: "Tab", mods: [ "CTRL", "SHIFT" ], action: "\x02p" } # previous window
- { key: "Comma", mods: [ "CMD" ], action: "\x02," } # rename window
- { key: "z", mods: [ "CMD", "CTRL" ], action: "\x02z" } # toggle zoom state
- { key: "t", mods: [ "CMD" ], action: "\x02c" } # create new tmux window
- { key: "x", mods: [ "CMD" ], action: "\x02x" } # kill current pane
- { key: "e", mods: [ "CMD" ], action: "\x02" } # split window horizontally 
- { key: "e", mods: [ "CMD", "SHIFT" ], action: "\x02%" } # split window vertically
- { key: "f", mods: [ "CMD", "SHIFT" ], action: "\x02\x5b\x2f" } # tmux search mode
- { key: "k", mods: [ "CMD" ], action: "\x02s" } # interactive tmux session
- { key: "j", mods: [ "CMD" ], action: "\x02\x54" } # smart tmux session
- { key: "l", mods: [ "CMD" ], action: "\x02l" } # tmux search session
- { key: "n", mods: ["CMD", "SHIFT"], action: "\x02N" } # new session
- { key: "k", mods: ["CMD", "SHIFT"], action: "\x02K" } # new session
- { key: "Comma", mods: [ "CMD", "SHIFT"], action: "\x02$" } # rename session

